version: '3.4'

services:
  crud-ddd.api:
    image: ${DOCKER_REGISTRY-}cruddddapi
    build:
      context: .
      dockerfile: CRUD-DDD.Api/Dockerfile
    depends_on:
      - crud.db
    ports:
      - "5000:80"
      
  
  crud.db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: mssqldb
    hostname: mssqldb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123#
    restart: unless-stopped
    ports:
      - "1433:1433"